### ISSUE TITLE
Consider making a plugin instead?

### ISSUE THREAD

**Issue by DavidRagone** [FundingCircle/dotvim#12]
I have my own vimrc that I've put some time into. I'm looking at what this setup uses, and am debating between (1) just using this one, (2) integrating the two into my personal vimrc (which I'm not crazy about, since I keep my vimrc on github), and (3) making the two play nicely together.

For the last option, the two things that come to mind are (a) sourcing this repo inside my own vimrc, and (b) using this as a plugin. I'm not sure how much work is involved in the plugin approach, but it might be fun to write one.

Thoughts, @dbolson || @yuhunglin?

**Comment by sgerrand** [comment]
@DavidRagone: A Vim plugin that installs a plugin manager to install plugins?

![yo dawg, I heard you like plugins](http://i.imgur.com/Nzq7Qyw.jpg)

**Comment by Mongey** [comment]
An alternative would be to allow overrides via a .vimrc.local 

```viml
" Local config
if filereadable($HOME . "/.vimrc.local")
  source ~/.vimrc.local
endif

```

**Comment by DavidRagone** [comment]
@sgerrand Isn't that exactly what Vundle.vim is?

@Mongey I like this approach. Seems much easier, just requires my personal vimrc being renamed (or symlinked to) `.vimrc.local`
